---
# The compiled PDF can be found here: https://github.com/ktmorris/blm_turnout/blob/master/markdown/blm_turnout.pdf
title: "Black Lives Matter Protests and Voter Turnout"
thanks: Prepared for the 2021 Annual Meeting of the American Sociological Association. Draft---please do not cite without permission. The authors thank XX for their feedback and support. All errors are our responsibility. 
author:
- Cameron Kimble^[Research and Program Associate, Brennan Center for Justice (cameron.kimble@nyu.edu)]
- Leanne Fan^[PhD Student, Department of Sociology, CUNY Graduate Center (lfan@gradcenter.cuny.edu)]
- Kasey Zapatka^[PhD Candidate, Department of Sociology, CUNY Graduate Center (kzapatka@gradcenter.cuny.edu)]
- Kevin Morris^[PhD Student, Department of Sociology, CUNY Graduate Center (kmorris@gradcenter.cuny.edu)]
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  bookdown::pdf_document2:
    toc: no
    fig_caption: yes
    latex_engine: xelatex
    keep_tex: true
bibliography: "blm_turnout.bib"
link-citations: yes
fontsize: 12pt
header-includes:
    - \usepackage{rotating}
    - \usepackage{setspace}
abstract: |
  In the summer of 2020, Americans took to the streets in larger numbers than ever before. Following the police murders of George Floyd and Breonna Taylor, an enormous multiracial coalition voiced their dissatisfaction with the state of policing in the United States. These mass protests took place shortly before a presidential election, and the incumbent loudly voiced his disdain for protesters and their political message. This paper explores one aspect of the impact of the Black Lives Matter (BLM) movement. Using a national voter file and data on protest location, we aim to estimate the causal impact of physical proximity to a BLM protest on voter turnout.
---
\pagenumbering{gobble}
\pagebreak
\doublespacing
```{r setup, echo = F, message = F, warning = F}
knitr::opts_knit$set(root.dir = "..", dev = "cairo_pdf")
library(systemfit)
library(kevostools)
library(AER)
library(sandwich)
library(lmtest)
library(scales)
library(ggpubr)
library(tidyverse)
library(extrafont)
library(kableExtra)
library(data.table)
library(stargazer)
loadfonts()
```
\pagenumbering{arabic}

Black Americans are subject to disproportionate interactions with the police, the carceral state, and the criminal justice system, more broadly. Against this backdrop, Black Lives Matter began as a twitter hashtag following the acquittal of George Zimmerman in the fatal shooting of Trayvon Martin [@Rickford2016].  Since then, BLM has evolved into a protest movement Either the intro to the whole piece or the beginning of the lit review will need more about Floyd's murder, the 2020 context, and background on BLM. Easy enough to add at the end
 
against racial disparities in economic, social and political outcomes.

## Protests & Turnout {-}

A large body of work in sociology has examined the influence of social movements, large-scale protests, and electoral politics. Key to this literature has been understanding how individuals’ beliefs and actions are shaped by social movements. @Lohmann1994 suggests that protest demonstrations reveal privately held information about dissatisfaction to the general public. Specifically, they raise awareness of social issues that result from prior policies with the aim of influencing voting decisions, as protest often signals intent to vote for or support a particular candidate or party. In going about their day-to-day lives, people acquire information regarding the consequences of various public policies, whether through factors such as changes in wealth, or general well-being, more broadly. At the level of individual experience, this may influence a single voter to prefer one candidate over another. But when people rally around an issue, through actions and demonstrations, this signals mass disaffection with the policy status quo. Collective action - a result of collective, shared experience -  then serves as a more accurate reflection of the consequences of policies. This information, at one point dispersed among many individuals, is now made public, sending a “loud” signal to both other, less-informed voters as well as political elites.     
Some researchers recognize the social environment as a mechanism to increase turnout by establishing norms of participation and providing networks to mobilize potential voters [@Rosenstone2003; @Verba1995]. Moreover, informal communication within social networks influences electoral behavior, as social pressure from within an individual’s network works as an inducement to political participation [@Gerber2008]. In fact, simply being informed of another’s actions in one’s community – or network – can increase an individual’s likelihood of voting [@Grosser2006].
It is important to note, however, that much of this work has focused on the effect of social pressures on turnout within a local context. For instance, Grosser et al. find that individuals, when informed of their neighbors’ turning out to vote, are more likely to vote themselves. They conclude that this neighborhood information effect increases turnout by nearly 50 percent. Similarly, Gerber et al., observed substantially higher turnout rates among those who received pre-election mailings promising to publicize the fact that they voted to their neighbors. But, more than a decade later, with the rise of Facebook, Instagram, and other forms of web-based communications, individuals may choose to publicize their decision to vote to their friends and neighbors online, and likely to a wider audience. 
While past work has focused on the relationship between geographical proximity and turnout, there is reason to believe that the BLM protests in 2020 operated differently than past social movements. The proliferation of social media, the nationalization of traditional media, and the polarization of Donald Trump’s re-election campaign turned local protests into a national issue. The 2020 BLM protests demonstrate how protest movements can raise awareness of social discontent and increase its salience in the mind of the public. Informational and network effects were amplified with the advent of social media, and by facilitating information exchange, sites like Twitter and Facebook make it easier for large groups of people to organize collective demonstrations. However, unique to the modern era is how these demonstrations are portrayed. Wasow [-@Wasow2020] offers the concept of agenda seeding to describe protestors drive media coverage and framing, congressional speech, and public opinion on civil rights, finding that nonviolent protests led to sympathy, especially when met with repression, and destructive protests led to themes centered on “law and order.” In the current political environment, portrayals of the protests differed along ideological lines, and so reinforced already existing political beliefs [see, for instance, @SignalAI2020].

Noting the gradual decline of local political news, researchers increasingly agree that American politics have become more and more nationalized in recent decades [@Fontana2018; @Moskowitz2021]. Indeed, to say “Donald Trump,” or in this case, Black Lives Matter “is to cue a set of meaningful associations with the national parties, the social groups that support them, and the positions that they take” [@Hopkins2018, page 2]. As such, we expect that proximity to a local BLM protest may have operated differently than social movements in the past. In particular, we expect the mobilizing effect at the local level was smaller than historical social movements. Given the polarization and prominence of national coverage, we suspect that individuals interpreted local protests through national media frames, and so were mobilized to vote for BLM and against Trump, or against “rioting” and for Trump. Whether the presence of social media and its heightening of network and informational effects motivated people to vote for or against Trump largely depends upon a person’s preexisting political beliefs, and thus their preferred media.  Put more simply, people motivated to vote by the BLM Movement voted in reaction to the national protest movement, not its local iterations.

Although we expect the local effects of BLM protests on *who* voted to be relatively small, the protests may have influenced *how* individuals voted. Scholars analyze the reciprocal relationship between social movements and elections more broadly than turnout alone. Political parties have attempted to capitalize on discontent by claiming issue ownership on social issues and including activists’ perspectives in their party platforms [@Fetner2008]. Grievance is harnessed by political parties to mobilize groups of voters[@Leege2002], and when social movements organized around a particular grievance challenge the status quo, mobilization efforts from the associated political party intensifies, in hopes of increasing voter turnout [@Winders1999]. As a result, protests that express liberal issues lead to a greater percentage of the two-party vote share for Democratic candidates, while protests that espouse conservative issues offer Republican candidates a greater share of the two-party vote [@Gillion2018]. Put differently, there is little evidence of an electoral “backlash”---that is, that social movements in support of liberal causes end up benefiting conservative candidates, and vice versa.

Demonstrating the reciprocal relationship between movements and elections, “Vote and Organize” became the motto for the BLM movement as election day grew nearer, the movements “get out the vote” effort reaching over 60 million households, according to one prominent national BLM activist [@Cullors2020]. At the same time, the Democratic Party continues to promote the BLM Movement and its issues.^[See https://democrats.org/black-lives-matter-organizing-resources/]  As such, while proximity to BLM protests likely did not affect voter turnout, the existence of the national BLM movement did.

# Protest & Political beliefs {-}

Start with paragraph about how even if protests didn’t influence turnout, it could have influenced beliefs.

There is no consensus on whether protest movements help or hurt in advancing their purported goals – affecting public opinion to change public policy. However, foundational research on political socialization indicates that initial frame alignment between an individual and a social movement organization is a precondition for participation [@Snow1986]. That frame alignment is a continuous process that occurs between individuals and social movements, transforming and reinforcing the individual’s ideological orientations. By their very nature, protest movements offer the opportunity for a frame realignment.

Research on how participation in (or exposure to) protest movements change individual political beliefs has largely focused on the Civil Rights Movement, a movement with which Black Lives Matter shares several similarities.  One study found that participating in the Freedom Summer project “radicalized” volunteers, who were then significantly more likely to participate in social movements in subsequent years [@McAdam1989]. Similarly, researchers conclude that involvement with social movements through the 1960s and 1970s caused a liberal shift in political orientation, as evidenced by subsequent political engagement such as voting for Jimmy Carter and participating in subsequent demonstrations [@Sherkat1997]. 

At a more macro level, Soumyajit Mazumder [-@Mazumder2018] finds that whites from counties that experienced civil rights protest are more liberal today, as measured by shifts in levels of racial resentment against African Americans, support for affirmative action, and identification with the Democratic Party. Moreover, this enduring attitudinal change is largely attributed to Civil Rights activists priming identities other than race (such as the American identity) and emphasizing ways in which whites and blacks were similar, causing whites to feel more sympathetic to black issues. On the contrary, Black Lives Matter activists invoke gender and LGBTQ+ frames in addition to race [@Tillery2019], which has been shown to reduce support for the movement, though not necessarily the movement’s goals [@Bonilla2020].

Finally, @Madestam2013 shows that Tea Party Movement rallies caused individual participants to become more politically conservative in their political views, increased public support for Tea Party positions, and led to more Republican votes in the 2010 midterm elections. Specifically, they find that the interactions produced at rallies and protests caused genuine shifts in political views, which sustained the momentum for a rightwards shift in fiscal policy going forward. We anticipate that the local Black Lives Matter protests had a similar effect among Democratic-leaning voters.

This is in line with the “social logic of politics,” [@Zuckerman2005] which centers social learning through interaction with others in development of political beliefs. Focusing events,” unexpected and visible events that harm a specific sub-population, such as the cellphone video of George Floyd’s killing, push issues related to said event to the top of public consciousness [@Birkland1998]. Moreover, theories of activated opinion suggest that minority-led protests often serve as a “bottom-up” factor that powers liberal shifts in public opinion [@Lee2002]. Thus, we anticipate that BLM protests caused those already sympathetic to BLM issues – Black voters and Democrats – to view the police in a less positive light.
At the same time, the police are a well-known and widely trusted institution, specifically among White Americans [@PewResearchCenter2019]. And given the centrality of police in popular imagination, as well as their receiving continued elite support, views on policing are difficult to change [@Zaller1992;@Nakamura2020]. We expect that while some white voters, those that lean Democratic, will view police less positively as a result of the BLM movement, the majority of white voters identify as Republicans, and so will associate the BLM protests with chaos. Most Republican voters will therefore view police more positively because of the protests; though we expect a minority of Republican voters to report less positive views of police following BLM protests, so that overall, white voter opinions on police remains constant, if not marginally less favorable. In short, we expect that the BLM protests probably further polarized Americans on issues surrounding policing.

# Data and Design {-}

We use a variety of data sources and empirical approaches to understand the electoral consequences of the 2020 protests in support of the Black Lives Matter movement. We are interested ultimately in the *causal* effect of protest exposure on these beliefs and behaviors, complicating our empirical approach. It seems highly probable that factors associated with protest formation are also associated with other political behaviors. Put differently, demonstrating a correlation between protest exposure and voting behavior might simply point to a third factor influencing them both. An example might be helpful: it seems possible that areas with large Black populations were politicized by the Trump Administration's response to the COVID-19 pandemic, which disproportionately impacted Black communities. This politicization---which may have occurred prior to the murder of George Floyd---could have increased an area's propensity to protest *and* increased their likelihood of voting in November. Thus, any correlation between protest and turnout would be due not to the protests themselves, but the underlying politicization.

To estimate the causal effect of protests on voter turnout, we leverage the known fact that protests are less likely to develop in inclement weather [CITE]. We use an instrumental variables (IV) approach that allows us to leverage random fluctuations in rainfall, the resulting protest formation, and eventual turnout and political behavior. IV setups are a common way for identifying causal relationships in the social sciences [CITE; CITE; CITE].

IV models do, however, have one very strict assumption: namely, the *exclusion restriction.* In other words, we must assume that our exogenous variable (here, rainfall) is unrelated to our dependent variable in any way other than through our endogenous variable (here, protest formation). If there is reason to believe that rainfall influenced turnout in November or political beliefs, our estimates cannot determine the causal relationship. There is reason to be particularly concerned with a violation of this assumption when using rainfall: as @Mellon2021 shows, nearly 200 journal articles have used rainfall as an instrument in recent years. That so many scholars have used rainfall as an instrument---that is, have argued that rainfall has a causal effect on many sorts of socially meaningful outcomes---challenges the validity of the assumption that rainfall impacts turnout only through protest formation. It is incumbent upon us, then, to demonstrate that the use of rainfall does not violate the exclusion restriction.

One way of improving the validity of our instrument is to use a region’s relative rainfall, not overall rainfall. It is possible, for instance, that protests were higher in areas of the country with generally rainy weather. Portland, Oregon, for instance, saw hundreds of protests over the course of 2020 and is notoriously rainy. If we used only absolute rainfall, we might incorrectly assume that protest formation was larger in generally rainier areas. Moreover, an additional inch of rain in a place like Oregon might impact protest formation less than in an arid climate like Phoenix. George Floyd was murdered on May 25, and protests began in the days that followed, and peaked the weekend of June 6 [@Buchanan2020]. As such, our instrumental variable is the amount of rainfall that fell between May 26 and June 7, 2020, scaled by historical rainfall. Specifically, we follow @Cooperman2017 in constructing a z-score for each weather station. The z-score is calculated as $\frac{x_{it} - \bar{x_{i}}}{s_{i}}$, where *x~it~* is weather station *i*’s 2020 rainfall; $\bar{x}$*~i~* is weather station *i*’s mean rainfall between May 26 and June 7 over the 1948--2019 period; and *s~i~* is the standard deviation of the annual rainfall of weather station *i* over the 1948--2020 period.

It is still possible, however, that relative rainfall in late May and early June could influence our dependent variables through other avenues. This seems especially likely if places with high relative rainfall in May and June *also* had high rainfall in late October---such high rainfall could then reduce turnout [CITE]. However, relative rainfall in the May--June period is only weakly associated with relative rainfall in late October (*r* = 0.07). We thus conclude that our approach satisfies the exclusion restriction.

## Data {-}

Our data come from a variety of sources. To estimate relative rainfall, we turn to the National Oceanic and Atmospheric Administration (NOAA), which collects detailed weather data from around the country. NOAA records the estimated daily rainfall at some 13,000 locations around the country. We use the `rnoaa` [@Chamberlain2021] package to download and process this data. The weather sites include each site's latitude and longitude.

Our data on protest formation comes from the U.S. Crisis Monitor, a project of the  Armed Conflict Location & Event Data Project (ACLED) and the Bridging Divides Initiative (BDI) at Princeton University.^[See https://acleddata.com/special-projects/us-crisis-monitor/.] The U.S. Crisis Monitor compiled geocoded data on BLM protests from around the United States throughout 2020. Using this data, we identify over 3,800 Black Lives Matter protests occurring between May 26 and June 7. These protests occurred in all 50 states and Washington, DC.

## Voter File Data {-}

To explore the relationship between protest exposure and individual-level turnout, we leverage the national registered voter file provided by data vendor L2. L2 collects the registered voter file from each state in the country and includes a host of self-reported and modelled information such as age, partisan affiliation, gender, and race / ethnicity. Importantly, they also indicate whether each voter participated in the 2020 general election, as well as past contests. L2 geocodes these records and maps them to their home census block groups. Taken as a whole, we have the individual-level voter records for the more than 200 million registered voters in the United States. Each record includes the voter’s historical turnout and their party of registration.^[In states without party registration, L2 uses proprietary models to estimate it, largely based on the primaries that voters have participated in.] 

There are some limitations to using the registered voter file to test for turnout effects. Most importantly, by looking at participation among registered voters, we may be "selecting" on the dependent variable [See @Nyhan2017]. In other words, registration *itself* is a form of political participation. If protest organizers registered many new voters at the protests---an approach that did apparently occur [CITE]---but only a relatively small share of these new registrants actually voted, the net result may have been *lower* turnout among registered voters (because the numerator grew less quickly than the denominator) but *higher* turnout among eligible citizens (additional ballots are introduced against a stable estimate of the eligible population unconditioned on registration).

To mitigate this potential problem, we aggregate individual records up to the census block group level to calculate the number of ballots cast in each block group in 2020 and previous elections. We use  Census Bureau data on  the citizen voting-age population (CVAP) as  a denominator for turnout that is not biased by differential registration rates. Turnout is thus calculated as the number of ballots cast according to the voter file, divided by the CVAP for that block group. We also use the registered voter file to determine the share of each block group that is registered as a Democrat or Republican. These estimates are then merged with demographic data from the 2015-2019 ACS 5-year survey such as median income, educational attainment, and median age.

Using an inverse distance weighting approach, we estimate the rainfall z-score for each block group in the country. This means that a given block group’s z-score will strongly reflect the z-score of the nearest weather station, but will also incorporate information from other nearby weather stations. The distance to a protest for each block group is measured from the centroid of the block group to the closest BLM protest. Ifa protest occurred anywhere within the block group, this distance is set to 0.


*H1*: Exposure to protest [increased / decreased] block group turnout. This was [especially / less] true for block groups with large Black populations.


## Addressing Spatial Dependence {-}
While aggregating individual voter turnout records to census block groups addresses some concerns, it raises new ones. Spatial dependence, or spatial autocorrelation, arises when “values observed at one location or region, say observation i, depend on the values of neighboring observations at nearby locations” [@LeSage2009, pg 2]. Since nearer things are more alike than distant things, a value on a given spatial unit is more affected by its neighbor than those farther away [@Tobler1970]. It is this similarity of values clustered in space that violates the “regression assumption that the error terms of individual observations can be considered independent of one another” [@Ward2008, pg 33]. This results in inflated standard errors that increase the possibility of Type 1 error of rejecting a true null hypothesis and can bias our regression estimates [@Ward2008].

There are three primary concerns of spatial dependence in our project. First, census block group turnout in one block group is likely to be very similar, and therefore spatially autocorrelated, with the turnout of those nearby because some characteristic that motivates political participation is likely clustered in space. Figure X provides visual evidence of this spatial dependence (first-order spatial effects) as we see clusters of dark (low turnout) and light (high turnout) values. Second, we are also concerned by spatial dependence in the outcome variable in our first stage model--distance from a protest. The distance of one block group is closely related to those of its neighbors because that block group and its neighbors by definition and block group construction are similar distances from a protest. Figure X also presents clear evidence of first-order spatial effects in that we see obvious clusters of both larger and smaller distances from BLM protests. Thirdly, we are also concerned about spatial dependence in our instrument, rainfall, since rainfall is not randomly distributed because neighboring block groups are more likely to “experience similar weather on any given day, and therefore our instrument naturally exhibits spatial correlation” [@Hansford2010, pg 281, see also @Betz2020]. Figure X illustrates this point very clearly. 

We confirm the statistical presence (second-order spatial effects) of spatial dependence with a global correlation coefficient known as a Moran’s I statistic, which tests for “a linear association of between a value and a weighted-average of its neighbors” and is often used as a test for spatial autocorrelation [@Ward2008, pg 23; @Bivand2013, pg 261]. Table X reports significant, preliminary, Moran’s I values for all three key variables: census block group turnout, distance from a protest, and rainfall across the country. Moran’s I values for turnout suggest moderate, positive autocorrelation (0.37), whereas distance reports weak, positive autocorrelation (0.25). Moran’s I for rainfall suggests very high, positive spatial autocorrelation (0.95). These results mean OLS and IV estimates are not reliable and we must correct for spatial dependence in both stages.

To correct for spatial autocorrelation in our models for all three variables, we follow a modern approach that suggests running either a Spatial Durbin Model (SDM) or a Spatial Durbin Error Model (SDEM), depending on whether we suspect global or local effects, and then using Log-likelihood Ratio (LR) tests to determine if a simpler, reduced model is more appropriate [@LeSage2009; @Burkey2018]. This approach is favored to a more classical approach pioneered by Luc Anselin [-Anselin1988] that uses the Lagrange Multiplier (LM) to decide model fit because it limits the range of models that can be considered to “only three types”” [Burkey2018, pg 16]. 

For both the first and second stages, we plan to run a SDEM instead of a SDM for three reasons.^[We avoid running a SARAR (SAC) model because there of its numerous drawbacks, specifically its sensitivity to misspecification [see @LeSage2014]] First, we suspect local, not global effects. By this we mean that although “neighbors affect each other, this effect does not propagate throughout the entire space” [@Burkey2018, pg 17]. So, we think neighboring block groups will have effects on those close by but not on all block groups in the country or even in the same state. Second, we prefer SDEM to SDM because it allows for lagged values of predictors. In the first stage, we want to correct for the non-random distribution of our instrument, rainfall, which we suspect will have effects on our outcome by definition of IV design, but also local effects on contiguous block groups, not all block groups throughout the country. In the second stage, we certainly think the share of black voters or population density (along with other controls) will have effects on our outcome and therefore their spatial dependence will need to be controlled. Third, SDEM is more efficient in our case. Although SDEM does not explicitly model spatial dependence in the form of a lagged outcome $\rho{Wy}$, which we certainly suspect, spatial dependence from the dependent variable will land in the disturbances, $\lambda{Wu}$, which are likely to produce a significant coefficient estimate for $\lambda$ that might be similar in magnitude to the true value of $\rho$ [@LeSage2014, pg 14]. Our SDEM models will take the following form: 

$$y = \alpha{} + X\beta_1{} + XW\beta_2{} + u$$ where $$ u = \lambda{Wu} + \epsilon{}$$

 
The LR approach then allows us to test whether reduced models are more appropriate in diagnosing the specific forms of spatial dependence we theorize. Using results from the LR tests and comparing the resulting “residuals for remaining spatial association” in our spatially adjusted models with those of reduced form (Spatial Error Models (SEM), Spatially Lagged X Model (SLX), and OLS) will help us determine which model specification, and therefore which estimates are most reliable in our IV setup [@Ward2008, pg 28]. We plan to replicate this analysis for our ZIP-code-level data for similar reasons.

## Survey Data {-}

While the administrative data gives us exceptional coverage of the relationships between protest and turnout across the country, turnout is a relatively blunt measure of political participation. Moreover, it seems possible that the BLM protests could have shifted voters' *beliefs* about topics such as the police without bringing new participants into the voting booth.

To understand the effect of protest exposure on political beliefs we turn to national survey data. We use two national surveys: the American National Election Study 2020 Time Series data (ANES) and the Cooperative Election Study (CES). Both are widely used among sociologists and political scientists to understand the political orientation of the American electorate. In addition to a rich set of data about individuals' political beliefs, these surveys also collect information about respondents' age, race, family income, and other characteristics. Each record includes the respondent's home ZIP code. ADD A LITTLE MORE ABOUT SURVEYS / SAMPLE SIZE / ETC

Once again, our empirical strategy relies on using rainfall as an instrument for protest exposure. In the case of the national survey data, however, there are not respondents from all ZIP codes in the country. As such, we run our IV models in two steps. We begin by predicting the distance from the center of each ZIP code in the country to the closest protest as a function of rainfall. To do so, each ZIP code is assigned the relative rainfall of the closest weather station (or the mean relative rainfall of all weather stations in the ZIP code). We then measure the distance from the center of the ZIP code to the closest BLM protest (this is coded as 0 miles if a protest occurred anywhere inside the ZIP code). The predicted distance for each ZIP code is then merged with the national survey data.

### Constructing Political Attitudes in the ANES {-}

TKTKTKTKTK [LEANNE]

### Constructing Political Attitudes in the CES {-}

TKTKTKTKTK [LEANNE]

# Results {-}



\newpage

# References {-}



